name: Production build
on: workflow_dispatch

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ✅
        uses: actions/checkout@v4
      - name: Can I deploy?
        uses: schedule-x/canideploy@v1.0
        with:
          timezone: 'Europe/Berlin'